all:
	g++ mailclient_ctrl.cpp mailclient_main.cpp client_GUI.cpp -o mailclient
#	g++ client_ctrl.cpp client_transport.cpp client_mailbox.cpp client_manager.cpp client_graphic.cpp client_ultility.cpp -o client

clean:
	rm ./mailclient
#	rm ./client